# Generated by Django 4.2.8 on 2023-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(max_length=40, verbose_name='Процессор')),
                ('ram', models.IntegerField(verbose_name='Оперативная память')),
                ('videocard', models.CharField(max_length=30, verbose_name='Видеокарта')),
                ('disk', models.CharField(max_length=20, verbose_name='Диск')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
